kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vision-reader-role
  namespace: {{ .Values.nameSpace }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]