pdnsHost: jenkins.ppe.sts.eun.azure.tesco.org

acr:
  dockerConfigJson: eyJhdXRocyI6eyJldW5wcGUwMjVzdHNjb250YWluZXJyZWdpc3RyeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiZXVucHBlMDI1c3RzY29udGFpbmVycmVnaXN0cnkiLCJwYXNzd29yZCI6IlFUUHM0V1kyNENNZUpiaThmbU9jTGU3ZVZ0eXI0dCtXIiwiYXV0aCI6IlpYVnVjSEJsTURJMWMzUnpZMjl1ZEdGcGJtVnljbVZuYVhOMGNuazZVVlJRY3pSWFdUSTBRMDFsU21KcE9HWnRUMk5NWlRkbFZuUjVjalIwSzFjPSJ9fX0=

appSP:
  clientId: YjJlYjRlM2QtZWY0MS00MTAwLTlhYmItOTlkMDQ0OTQ1ODgx
  clientSecret: T2kxMXFLNDJ0VVN6YkNvcw==
  tenantId: ZjU1YjFmN2QtN2E3Zi00OWU0LTliOTAtNTUyMThhYWQ4OWY4