pdnsHost: dev-jenkins.zone.sts.dev.eun.azure.tesco.org

acr:
  dockerConfigJson: eyJhdXRocyI6eyJldW5kZXYwMjVzdHNjb250YWluZXJyZWdpc3RyeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiZXVuZGV2MDI1c3RzY29udGFpbmVycmVnaXN0cnkiLCJwYXNzd29yZCI6Ims1ODVsd2puU1BSTlBCckUzeENvU3VXeUt4MlpjK2Z0IiwiYXV0aCI6IlpYVnVaR1YyTURJMWMzUnpZMjl1ZEdGcGJtVnljbVZuYVhOMGNuazZhelU0Tld4M2FtNVRVRkpPVUVKeVJUTjRRMjlUZFZkNVMzZ3lXbU1yWm5RPSJ9fX0=

appSP:
  clientId: YjJlYjRlM2QtZWY0MS00MTAwLTlhYmItOTlkMDQ0OTQ1ODgx
  clientSecret: T2kxMXFLNDJ0VVN6YkNvcw==
  tenantId: ZjU1YjFmN2QtN2E3Zi00OWU0LTliOTAtNTUyMThhYWQ4OWY4