nameSpace: sts-ppe-recon

aadGrpIds:
  contributor: e65b0ad9-ba15-4d43-b1e1-4b98c83f593d
  reader: a2cc2309-d13d-4e05-9908-640bf0f7cf88

appSP:
  clientId: YzA3NTIzOWEtZWU2NC00Nzg5LTllMTctNTg2NjU4Nzg1YTU0
  clientSecret: SlZXbEltWC5qQlA4Qy5RIw==
  tenantId: ZjU1YjFmN2QtN2E3Zi00OWU0LTliOTAtNTUyMThhYWQ4OWY4

acr:
  dockerConfigJson: eyJhdXRocyI6eyJldW5wcGUwMjVzdHNjb250YWluZXJyZWdpc3RyeS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiZXVucHBlMDI1c3RzY29udGFpbmVycmVnaXN0cnkiLCJwYXNzd29yZCI6IlFUUHM0V1kyNENNZUpiaThmbU9jTGU3ZVZ0eXI0dCtXIiwiYXV0aCI6IlpYVnVjSEJsTURJMWMzUnpZMjl1ZEdGcGJtVnljbVZuYVhOMGNuazZVVlJRY3pSWFdUSTBRMDFsU21KcE9HWnRUMk5NWlRkbFZuUjVjalIwSzFjPSJ9fX0=

pdnsHost: internalaks.ppe.sts.eun.azure.tesco.org

#used in store service.
decryptKey: ZnJzLXBwZS1wd2Qtc3RvcmUtc2VydmljZQ==