kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: recon-contributor-role
  namespace: {{ .Values.nameSpace }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]